### ISSUE TITLE
Print unrolled call stack in debug builds on assertions?

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#100]
This would be a pure convenience feature, to shorten the `assertion -> run again in gdb -> bt cycle`, since gdb takes a while to load for insieme, and running larger programs also can take a while.

I think whether it's worth it depends on how good the tools are to do it -- and preferably without introducing an extra dependency. If I understand `backtrace_symbols_fd` correctly, it should basically be a one-liner.

Thoughts?

**Comment by HerbertJordan** [comment]
It is becoming like Java. Other than that, sure, go for it :)

**Comment by PeterTh** [comment]
Completed in https://github.com/insieme/insieme/commit/c4af7aa9a48a3a99c98c6d41da81d41fba1658e0 and https://github.com/insieme/insieme/commit/ca43a1ec97125806d6942976a0e2651d66fbf506,
