### ISSUE TITLE
Bugs in C++11 lambda conversion

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#103]
I experienced a problem when converting C++11 lambdas into IR code.
Following code produces non-sense IR and target code:
```
typedef int (*fptr)();

int d(fptr&& x) {
 x();
}

int main() {
 int a = d([]() { return 10; });
}
```
The code compiles but the body of the lambda is never called.
Anyway, the produced IR looks like:
```
let type000 = struct<
	_rval_cpp_ref:ref<() -> int<4>>
>;

let fun000 = fun(type000 v2) -> int<4> {
    return ( *RefRValCppToIR(v2))();
};

let type002 = struct _anonRecord_insieme_dev_stefanm_ext_t_cpp2215 <
	
>;

let fun001 = fun() -> int<4> { };

let fun002 = mfun type002 v62 :: () -> () -> int<4> {
    return fun001;
};

let fun003 = fun() -> int<4> {
    decl ref<int<4>> v57 = ( var(fun000(RefIRToRValCpp(( var(fun002(( var(struct{})))))))));
    return 0;
};

// Inspire Program 
//  Entry Point: 
fun003
```
Sema checks are ok but as you can see: The var init of the lambda (first line of fun003) is ok.
The call (and even the existence) of fun002 and fun001 is wrong because it returns invalid things
and should not be there. fun000 is fine again. 

Don't worry about the rval ref in the input code. It is also possible to reproduce this issue without
rval refs. Just use a const cpp fptr ref instead of the rval ref.

**Comment by HerbertJordan** [comment]
What would be interesting to see is the Clang AST that is generated for 
```
d([]() { return 10; })
```
in your example. I guess it contains clues to model this properly.

**Comment by stefanmoosbrugger** [comment]
The AST for the vardecl (a) looks like:

```
VarDecl 0x1d7d100 <t.cpp:22:5, col:34> a 'int'
`-CallExpr 0x1d7d8f0 <col:13, col:34> 'int'
  |-ImplicitCastExpr 0x1d7d8d8 <col:13> 'int (*)(fptr &&)' <FunctionToPointerDecay>
  | `-DeclRefExpr 0x1d7d858 <col:13> 'int (fptr &&)' lvalue Function 0x1d7ce80 'd' 'int (fptr &&)'
  `-MaterializeTemporaryExpr 0x1d7da78 <col:15, col:33> 'fptr':'int (*)(void)' xvalue
    `-ImplicitCastExpr 0x1d7da60 <col:15, col:33> 'int (*)(void)' <UserDefinedConversion>
      `-CXXMemberCallExpr 0x1d7da38 <col:15, col:33> 'int (*)(void)'
        `-MemberExpr 0x1d7d970 <col:15, col:33> '<bound member function type>' .operator int (*)(void) 0x1d7d520
          `-ImplicitCastExpr 0x1d7d958 <col:15, col:33> 'const class <lambda at t.cpp:22:15>' <NoOp>
            `-LambdaExpr 0x1d7d670 <col:15, col:33> 'class <lambda at t.cpp:22:15>'
              |-CXXRecordDecl 0x1d7d200 <col:15> class definition
              | |-CXXMethodDecl 0x1d7d330 <col:18, col:33> operator() 'int (void) const' inline
              | | `-CompoundStmt 0x1d7d420 <col:20, col:33>
              | |   `-ReturnStmt 0x1d7d400 <col:22, col:29>
              | |     `-IntegerLiteral 0x1d7d3e0 <col:29> 'int' 10
              | |-CXXConversionDecl 0x1d7d520 <col:15> operator int (*)(void) 'int (*(void) const)(void)' inline
              | | `-CompoundStmt 0x1d7da00 <col:15>
              | |   `-ReturnStmt 0x1d7d9e0 <col:15>
              | |     `-ImplicitCastExpr 0x1d7d9c8 <col:15> 'int (*)(void)' <FunctionToPointerDecay>
              | |       `-DeclRefExpr 0x1d7d9a0 <col:15> 'int (void)' lvalue CXXMethod 0x1d7d5d0 '__invoke' 'int (void)'
              | |-CXXMethodDecl 0x1d7d5d0 <col:15> __invoke 'int (void)' static inline
              | | `-CompoundStmt 0x1d7da20 <col:15>
              | `-CXXDestructorDecl 0x1d7d6c0 <col:15> ~ 'void (void) noexcept' inline
              |   `-CompoundStmt 0x1d7d7d8 <col:15>
              `-CompoundStmt 0x1d7d420 <col:20, col:33>
                `-ReturnStmt 0x1d7d400 <col:22, col:29>
                  `-IntegerLiteral 0x1d7d3e0 <col:29> 'int' 10
```

**Comment by HerbertJordan** [comment]
I guess the stack of `MaterializeTemporaryExpr`, `ImplicitCastExpr`, `CXXMemberCallExpr`, `MemberExpr` and `ImplicitCastExpr` has to be intercepted by some frontend extension to perform the following steps:
* take the struct-init expression that is returned by the nested `LambdaExpr` conversion
* lookup the member function `operator()` associated to this struct 
* take the IR-lambda expression describing this function and remove the first parameter (this parameter), as well as reduce the type from a member-function type to a plain function type
* take the resulting lambda and convert it to a `src<fun-type>` using e.g. `ref.var`

**Comment by stefanmoosbrugger** [comment]
Ok, but one question. How should we handle captured variables?

**Comment by HerbertJordan** [comment]
Lambdas with captured values can not be converted into function pointers. This a restriction imposed by the C++ standard.

**Comment by stefanmoosbrugger** [comment]
The code above is exactly what should be generated. Clang is giving us an incomplete AST. We see a call to the static ```__invoker``` function that contains an empty body only. Anyway, commit https://github.com/insieme/insieme/commit/6ded5703af5ad9c351af64588af4206983485248 should fix this issue.
