### ISSUE TITLE
Create backups of sources of external dependency libraries

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#104]
The sources of external library dependencies should be backed up in common repository to mitigate the risk of losing a dependency due to broken URLs or lost 'older versions' (as encountered during installation process -- sourceforge is down at the moment).

**Comment by peterz-dps** [comment]
I'd say we definitely need that. I guess for some libraries I had to change the URLs now twice already, with other people doing the same in between. Since we really seem to strongly depend on specific versions we should consider keeping these available somewhere...
