### ISSUE TITLE
Delay or even remove additional backend compiler calls

### ISSUE THREAD

**Issue by philippgs** [insieme/insieme#111]
I noticed that ```insiemecc``` calls the backend compiler to check for default system include directories, even when only called with ```--help```. This is due to nested member fields, the innermost of which is of type ```ConversionSetup```, whose constructor initializes a vector with the result of this call.

Is there another, standardized way of getting/assuming system include directories, or should we delay getting the include directories to when they're actually needed? Intuitively, if ```insiemecc``` is not asked to compile-to-binary, a working backend compiler seems to be a potentially unnecessary dependency, even more so when only requesting ```--help```, ```--version``` or alike.

**Comment by HerbertJordan** [comment]
As far as I know the system header file directory is required by the frontend. But for sure this could be moved into a lazy-evaluated value (there is a util for that) such that the gcc system call is only conducted if required.

**Comment by PeterTh** [comment]
I'll fix this, should be easy enough.

**Comment by PeterTh** [comment]
Done.
