### ISSUE TITLE
Insieme - try out INSPIRE

### ISSUE THREAD

**Issue by ncos** [insieme/insieme#114]
Hi,

I want to examine how Insieme processes and keeps information about parallel algorithms inside INSPIRE. I am especially interested in the implementation of INSPIRE generation and the way different parallel constructs are handled inside your compiler.

It looks like you have the current development branch and 4 year old 0.5 version. Could you please specify the difference between them? Are there any release notes?

Thank you for your answer

**Comment by philippgs** [comment]
To my knowledge, there are no release notes available online, but there's a wiki page https://github.com/insieme/insieme/wiki/Inspire-20xy that lists most of what we intend to do and also links a few relevant github issues. In a nutshell, we changed the specs of INSPIRE with regard to 

* pointers, arrays and C++ references
* C++ classes and qualifiers
* call semantics and object lifetime

Almost all of this work aims at "making the parsing of C code easier and making the parsing of C++ code possible" (quoting @PeterTh), and is not directly targeted at changing how we handle parallelism. The old inspire_1.3 branch already successfully parses a lot of C++ code, but very likely not to the extend of the master branch when it is finished and definitely not as cleanly. However, as a result, we have to rewrite major parts of the core, the frontend and the backend. But again, this is mainly targeted at C++ support.

**Comment by HerbertJordan** [comment]
Hi,

regarding the parallel constructs: I guess the best introduction is provided by [this thesis](http://www.dps.uibk.ac.at/~csaf7445/pub/phd_thesis_jordan.pdf) which you can find among all our [publications](http://insieme-compiler.org/publications.html) and [thesis](http://insieme-compiler.org/theses.html) on our [project webside](http://insieme-compiler.org).

In the referenced thesis you are probably mostly interested in Chapter 3, in particular Section 3.3.2 for a general overview, Section 3.4.2 for the syntax, Section 3.7.2 (starting from page 109) for the formal specification of the semantic of the utilized parallel constructs and Section 3.9 for examples on how to convert parallel language constructs of source codes into inspire. For advanced topics, Chapter 4 provides a description of our analysis frameworks we developed on top of our IR.

A short overview on all those topics is also covered by [this paper](http://dl.acm.org/citation.cfm?id=2523721.2523727).

Note that the current overhaul is not effecting any of the parallel constructs, only the sequential 'host' language.

**Comment by PeterTh** [comment]
I hope this question has been answered sufficiently, if not, reopen the issue.
