### ISSUE TITLE
Enum implementation

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#118]
The enum implementation needs to be refactored to
* keep track of numeric value assignments in the input code ( `enum A { B = 15, C = 7 }` )
* ideally allow implementing the to int / from int conversions as derived operators, transparent to analysis

Proposal: enum expressions mapped to structs of the following shape:
`struct A { enum<entry<B, 15>, entry<C, 7>, ...> _unused; int<'a> value }`

**Comment by PeterTh** [comment]
Relevant part of the C standard:
(we should be fine always using int<8> and num_casting that to whatever is required in the context)

## 6.7.2.2 Enumeration speciﬁers
#### Constraints
The expression that deﬁnes the value of an enumeration constant shall be an integer constant expression that has a value representable as an int.
#### Semantics
The identiﬁers in an enumerator list are declared as constants that have type int and may appear whereversuch are permitted. An enumerator with = deﬁnes its enumeration constant as the value of the constant expression. If the ﬁrst enumerator has no =,the value of its enumeration constant is 0. Each subsequent enumerator with no = deﬁnes its enumeration constant as the value of the constant expression obtained by adding 1 to the value of the previous enumeration constant. (The use of enumerators with = may produce enumeration constants with values that duplicate other values in the same enumeration.) The enumerators of an enumeration are also known as its members.
Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-deﬁned, but shall be capable of representing the values of all the members of the enumeration. The enumerated type is incomplete until after the } that terminates the list of enumerator declarations.

**Comment by HerbertJordan** [comment]
The enum extension in the core should contain derived operators for the conversion of enum values to integers and vice versa.

**Comment by HerbertJordan** [comment]
Implementation details to proposed solution:
def
##### Type: 
Given: C-enum like 
```
enum Color { RED = 1, BLUE = 2, GREEN = 4 };
```

Inspire enumeration type encoding:
```
struct _enum_ {
    enum_def<Color,entry<RED,1,entry<GREEN,2,entry<BLUE,3>>>> def;
    int<8> value;
}
```

##### Operators: 
Based on this type definition pattern the following operators can be encoded: 

Conversion from enum value to integer value:
```
(struct _enum_ { enum_def<'name,'domain> def; int<8> value; } e) -> int<8> { 
    return e.value; 
}
```

Conversion from integer value to enumeration value:
```
let enum = struct _enum_ { enum_def<'name,'domain> def; int<8> value; } in
(int<8> v, type<enum> t) -> enum { 
    return struct enum { lit("def" : enum_def<'name,'domain>), v }; 
}
```

Comparison operators like e.g. equals:
```
let enum = struct _enum_ { enum_def<'name,'domain> def; int<8> value; } in
(enum a, enum b) -> bool { 
    return a.value == b.value; 
}
```

##### Semantic Checks:
- all enum structs must have a valid definition field
  - name field must be a simple, generic type
  - domain must be a valid list of entries
-  no other literal of type enum_def<'a,'b> than the one with value "def"
