### ISSUE TITLE
Create a dependency system for the frontend plugins

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#12]
Create a dependency system for the frontend plugins to ensure a valid processing order.

+ print at loglevel Log::Info the enabled plugins (enabled by user/by dependency)

**Comment by berhoeckner** [comment]
After discussion it was realized that we don't want a full dependency system (currently) as there is no real use-case.
For now it's sufficient that each plugin has the ability to check if its prerequisites are fulfilled.
If these prerequisites are not fulfilled the plugin should provide an expressive log message. The ConversionJob needs to handle the failing case, most probably by aborting and printing the log message.
