### ISSUE TITLE
Core Data Structures generated by Script

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#124]
The IR node definitions currently created utilizing a mixture of template instantiations and macro expansions should be replaced by code structures generated from some input configuration file. As all generated sources, those files should not be included in the repository but utilized for building the code.

This might also help in improving the IDE code completion support for most editors.

**Comment by PeterTh** [comment]
By simplifying how accessors are generated, we were able to achieve the primary benefit of this (code completion on core structures in multiple IDEs) without introducing the infrastructure overhead of a separate scripting pass.
