### ISSUE TITLE
Find a tool to clean up the whole codebase.

### ISSUE THREAD

**Issue by peterz-dps** [insieme/insieme#125]
During our big refactorings in the core we already stumbled upon several functions which aren't used by anybody anymore and probably haven't been used in years.
In the whole project there is probably a whole lot of functionality which nobody ever uses. We should find a tool which analyzes our whole codebase and dispalys some candidates for deletion, to clean up the code.

**Comment by HerbertJordan** [comment]
The clang based tool

http://clang-analyzer.llvm.org/

could be a promising tool -- however, we need clang to compile Insieme and the version on my system is not capable of doing so.

**Comment by PeterTh** [comment]
We could also use a code coverage tool in combination with our unit tests. This would have the additional advantage of also pointing out code parts not hit in any unit test (even if they are statically "used" in the code).
