### ISSUE TITLE
Storage class 'extern' is lost for global variables

### ISSUE THREAD

**Issue by sp4r74n-117** [insieme/insieme#130]
Input:
extern int g_external;
int main(int argc, char** argv)
{
	g_external = 0;
	return 0;
}

IR-Dump:
decl fun000 : (int<4>, ptr<ptr<char>>) -> int<4>;
def fun000 = function (v341 : ref<int<4>,f,f,plain>, v342 : ref<ptr<ptr<char>>,f,f,plain>) -> int<4> {
    c_style_assignment(g_external, 0);
    return 0;
};

TRG-Dump:
...
/* ------- Global Variable Declaration ---------- */
int32_t g_external;
...

**Comment by PeterTh** [comment]
Fixed as of https://github.com/insieme/insieme/commit/e2fdf7e50a65edcc6505b2e7d9c47c64a8b0ebae
