### ISSUE TITLE
Needed: Jenkins release mode build without assertions

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#132]
Commit a3657d8d8e450e1512aad90047df655950a5bce8 fixed an issue where a DEATH_TEST was used to verify that an assertion was effectively protecting the creation of some data structure. However, this assertion will not be triggered in release mode.

The problem was not discovered since the jenkins release mode is building with assertions. To make sure the projekt can be successfully build and tested in release another jenkins configuration should be added.

**Comment by philippgs** [comment]
done
