### ISSUE TITLE
Parser support for 'free' constructors and member functions

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#135]
Inspire allows constructors and member functions to be defined outside the actual tag type to enable local specialization. For instance, something similar to the example
```
def struct A { ... };
def free_ctor = A::(int x) { ... };
def free_mfun = A::(int x)->int const { ... };

int main() {
   var ref<A> a = free_ctor(ref_var(type_lit(A)), 10);
   a.free_mfun(12);
}
```
should be possible. The free constructor and member function are not to be included in the `TagType` A itself, but represented as a local lambda of the corresponding type. This is important to enable the local modification of constructors / member functions without the requirement of modifying all the instances of types A throughout the entire program.

Also note: there are no free destructors nor free virtual functions. The former can not be supported in general, the later will be covered by the virtual dispatch node to be introduced soon.

**Comment by peterz-dps** [comment]
Implemented by b4f6fbbaf7cfbbc12a08d20d5f0b7531f4140763
