### ISSUE TITLE
Generate cleaner for loops in the frontend

### ISSUE THREAD

**Issue by philippgs** [insieme/insieme#14]
Generate cleaner for loops in the frontend e.g. by pre-evaluating conditions such as (x < 9+1) to (x < 10) to simplify testing

**Comment by HerbertJordan** [comment]
(if not obvious) Hint: use the core's arithmetic facilities

**Comment by klois** [comment]
Done, as far as it will go, with https://github.com/insieme/insieme/commit/e88aa6330c17b4ed208571cd8340581752225edc
