### ISSUE TITLE
Issue with vector derived operators and CBA

### ISSUE THREAD

**Issue by LuisAyuso** [insieme/insieme#16]
CBA unstable when deriving IR constructions, VectorInitUniform makes ut_analysis_cba_test_sequential fail (I presume is the arithmetic analysis when dealing with intTypeParams passed to a function) 

To trigger this error, change the Uniform Vector Initialization to use derived operator in Lang.def (now vectors.def)

**Comment by peterz-dps** [comment]
This issue might depend on issue #21

**Comment by HerbertJordan** [comment]
It is independent of issue #21, yet has the same cause. I guess some data-flow constraints are missing regarding int-type parameters to deduce the size of the initialized arrays or such.

What exactly is failing? Is it seg-faulting or are the results incorrect?

**Comment by PeterTh** [comment]
Not relevant to the current master branch any more.
