### ISSUE TITLE
Implement Frontend Extension prerequisite checking

### ISSUE THREAD

**Issue by berhoeckner** [insieme/insieme#18]
Check if prerequisites of a given Frontend Extension are fullfilled. For example may FE Extensions depend to be setup before/after another FE Extension. 
Furthermore a FE Extensions should provide an expressive log message if the requisites are not fulfilled.

**Comment by HerbertJordan** [comment]
For the logging part: i would add corresponding interfaces to the plugin mechanism to provide control on those on the framework level -- not the global logging (which should be revised too at some point) 

Also, try to design the API to be as fool-proof as possible, e.g. by requesting explicit lists of handled operatores or language constructs and check for collisions within the framework.

**Comment by berhoeckner** [comment]
After some discussion, we realized that most extensions are currently independent. Only some should have a somehow fixed position (InterceptorExtension - in the front, the CleanupExtension - in the end, AnonymousRenameExtension - in the end). This can be handled by checking the position in the list of extensions.

The effort to introduce a full-framework to check and define dependencies based on the operators/language constructs would take the same amount as implementing the extension itself. As there is currently no need (see above) i will not implement this.

What is implemented (by stefanmoosbrugger) is that a Extension can define its own options to be offered via the driver, and these are checked.

**Comment by PeterTh** [comment]
https://github.com/insieme/insieme/commit/9642a06a5b04e51ad3295c273751c995f7951198
