### ISSUE TITLE
Fix parentheses in pretty printer output

### ISSUE THREAD

**Issue by klois** [insieme/insieme#20]
The pretty print of e.g.

	(uint.sub(uint.sub(20u, 10u), uint.mul(uint.div(uint.sub(20u, 10u), 1), 1))

should be 

	(20u-10u)-(20u-10u)/1*1
	
but is

	20u-10u-20u-10u/1*1

**Comment by PeterTh** [comment]
We have the same issue in the C backend, where it is solved.
Ideally, the same solution should be used in both the prettyprinter and the C backend.

**Comment by HerbertJordan** [comment]
The backend is dealing with this issue while building the C-AST bottom up. Whenever a binary operator is utilized to connect two nodes the precedence of the operators is compared with the precedence of the operator, and if necessary parenthesis are inserted. 

This is rather tightly interwoven with the C-AST node structure:
https://github.com/insieme/insieme/blob/master/code/backend/include/insieme/backend/c_ast/c_ast_utils.h#L383-L392

**Comment by klois** [comment]
Fixed with https://github.com/insieme/insieme/commit/c15fa97dd314a60fa981fe1f6d8b5919c7ea5310
The PrettyPrinter flag PRINT_BRACKETS has been renamed to SKIP_BRACKETS which is turned off by default.
