### ISSUE TITLE
Fix OpenCL backend for new JobExpr

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#3]
JobExpr declarations were removed, breaking the OpenCL backend recognition. Fix backend.

**Comment by PeterTh** [comment]
Isn't this done with https://github.com/insieme/insieme/commit/38bf1ad594db2fa8a30d4fcaffe14fb948e8e9da?

**Comment by stefanmoosbrugger** [comment]
Basically done. But there are still some integration tests to fix,
but afaik the tests are quite new (ivan wrote them) and I don't know
if they worked before the change.

**Comment by stefanmoosbrugger** [comment]
fixed remaining issues with https://github.com/insieme/insieme/commit/b95ef6c1b0a5613cc65c9421168edfd3f1eca0e8
