### ISSUE TITLE
Check why --no-as-needed linker flag is used in integration tests

### ISSUE THREAD

**Issue by peterz-dps** [insieme/insieme#31]
Is this flag really needed or was it just added to fix some linking problems?

**Comment by philippgs** [comment]
Adding to that, one could also check all flags that are given to insiemecc in the integration tests - there are some that are deprecated, e.g. formatting flags regarding the column width of the output.

**Comment by philippgs** [comment]
And we could drop setting environment variables in 90% of the cases when they are set without adding new content, i.e. `LD_LIBRARY_PATH=$LD_LIBRARY_PATH`.

**Comment by philippgs** [comment]
https://github.com/insieme/insieme/commit/ab4d6d3ba259eee7b6a1fec1bb86045ad79f0cf7 removes all occurrences of `--no-as-needed`, without any apparent issues. I also took care of the other flags and the `LD_LIBRARY_PATH` variable (in another commit, in case we ever decide to revert either one).

**Comment by HerbertJordan** [comment]
The build on my system fails when removing the flag from *environment.cmake*.

The error message indicates that symbols from the pthread library are not available to the gtest library.

**Comment by philippgs** [comment]
That leads me to assume that we link stuff in an incorrect order in our CMake scripts. I will have a look and try to reorder stuff.

I also remember that @klois hat a similar issue regarding gtest and `pthread_key_delete`, and we (possibly errouneously) contributed it to a system update he previously performed...

**Comment by klois** [comment]
When removing the --no-as-needed flag from environment.cmake linking fails on both my office and my home PC.

**Comment by philippgs** [comment]
Ok, @klois and I just tested a temporary solution, which is setting

    LDFLAGS="-Wl,--no-as-needed" 

before running `cmake`. We will make sure that the linking order is correct in the new CMake scripts.

**Comment by igsoft** [comment]
It seems that the new CMAKE solved this issue.
