### ISSUE TITLE
Upgrade of parser for proper error reporting and tracing of source code locations

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#32]
The current version of the parser is a all-or-nothing parser which is not capable of narrowing down parsing errors to confined source code locations. The increased utilization of the parser, however, may justify a work over compensating for this shortcoming.

Alternative: utilize a sophisticated parser generators to build a fast parser with accurate error reporting

**Comment by LuisAyuso** [comment]
Parser 3 is happening, thanks for asking.

**Comment by LuisAyuso** [comment]
The new parser infrastructure is under development, it uses: 
http://www.gnu.org/software/bison/manual/html_node/Simple-GLR-Parsers.html

- Reduces codebase in 2k lines of code,
- provides separated lexer/parser/sema errors.
- is (at least) twice as fast as previous parser.

I might need around another month to finish it.

**Comment by LuisAyuso** [comment]
What is a real issue is the separation of printer syntax and parser syntax, this should be unified and enforced. the earlier, the better.

**Comment by HerbertJordan** [comment]
Agreed. 

Volunteers?

**Comment by LuisAyuso** [comment]
it is already one month of development

**Comment by LuisAyuso** [comment]
The parser 3 is pushed, 
Still work to do, the source location can be improved, 
I close this tikets, for anything issue, open a new one.
