### ISSUE TITLE
Think again about type literals

### ISSUE THREAD

**Issue by peterz-dps** [insieme/insieme#34]
We made a small change to type literals yesterday (4fa067092bdcfd1e8169701ab5e70763fdb08418) in order to handle the problem of the information within type literals going out of sync when the type part is changed. As the string value will not be updated this might cause troubles in analysis and further processing of these nodes.

We discovered this because the PrettyPrinter and the dumpDetail seem to handle these differently and show different results when printing TypeLiterals which's type representation has been transformed.

Our fix will cause the StringValue to be re-computed every time one asks for it on type literals, but this is actually not an ideal solution.

One might argue that we should introduce a new node type specifically for type literals as type literals don't really have a is-a relationship with literals (their string value is meaningless and not updated if the representation of the type changes)

On the other hand, introducing a new node type might cause lots of changes downstream, so we'll have to think about possible solutions for this issue.

**Comment by PeterTh** [comment]
One additional note: the real problem is not just that the are printed differently, but that the string value is a /semantically meaningful/ part of the literal, so if it differs the actual literal differs, even when referring to the same type.
Our "fix" mitigates this issue by giving all type literals the same string value.

**Comment by HerbertJordan** [comment]
I think the introduction of a type-literal node type is a good idea and we should add it to the list of IR revision #29.

For now a semantic check that verifies that the string value of a type literal is indeed 'type_literal' should be added to discover issues if they occur. 

Also the same arguments are valid for int-type-parameter-literals, which follow the same principle.

**Comment by peterz-dps** [comment]
I added a semantic check verifying this (a741db258f5411ac8dad17aec2b8f7183f882999).

While doing so we also found another location where TypeLiterals are created which needed to be adapted to behave like the builder does now (f84b32040fb12715459826fe157f2f74694b2448)

I don't know whether we should close this ticket here since the introduction of TypeLiterals (as well as IntTypeParamLiterals) has now already been added to issue #29.

**Comment by HerbertJordan** [comment]
If it is working for now, close it. #29 will do the rest.
