### ISSUE TITLE
Simplifying loop boundaries causes segmentation fault in the polyhedral model

### ISSUE THREAD

**Issue by philippgs** [insieme/insieme#36]
https://github.com/insieme/insieme/commit/8eaa63cfe616f2afcd683646562e120d02535481 seems to cause the polyhedral library to issue a nullptr dereference in some cases when trying to apply tiling. I will try to work out an MWE. Related to #14.

**Comment by klois** [comment]
I'd guess that a nullptr dereference can only be caused by that change if core::transform::simplify returns NULL. Try to check for that in those cases...

**Comment by PeterTh** [comment]
Immaterial in current master.
