### ISSUE TITLE
Invalid IR code generated by the runtime-backend pre-processors

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#37]
One of the runtime backend pre-processors is generating invalid IR code. The corresponding assertion has been disabled or performance reasons, thus it remains undetected. But it should be fixed.

**Comment by philippgs** [comment]
In case these assertions were really disabled for performance reasons only, we should consider enabling them e.g. for `Debug` type builds.

Alternatively we could follow up with the idea of creating a Jenkins job that runs e.g. just once a week but performs more extensive testing. This would require a new build type, preprocessor flag or alike.

**Comment by HerbertJordan** [comment]
I have fixed a minor issue regarding the encoding of type literals connected to the forwarding of arguments to work items. However, i discovered that various sources hand in IR code including semantic errors to the backend as well.

By enabling
https://github.com/insieme/insieme/blob/master/code/backend/src/converter.cpp#L77-L78
those incoming erros can be identified. Once resolved, the assertion
https://github.com/insieme/insieme/blob/master/code/backend/src/converter.cpp#L83-L84
should be enabled to ensure the proper working of the backend-preprocessors.

**Comment by PeterTh** [comment]
The check referenced above is enabled in current master. 
I'm assuming the issues are resolved.
