### ISSUE TITLE
Ensure proper linking order in integration tests

### ISSUE THREAD

**Issue by philippgs** [insieme/insieme#40]
While it might be already correct by accident, proper linking order should be ensured for the integration tests, to increase stability for future codes (due to gcc's default `--as-needed` behavior in versions >4.6)

E.g.

    gcc -lsomelibrary object.o -o output

should become

    gcc object.o -lsomelibrary -o output

**Comment by PeterTh** [comment]
I've seen stuff like this as well:
`gcc -lsomelibrary object.o -lsomelibrary -o output -lsomelibrary`
