### ISSUE TITLE
Test for ir++_extensions

### ISSUE THREAD

**Issue by LuisAyuso** [insieme/insieme#41]
The current test for ir++_extensions requires of developers writing a specific test for every construct, added constructs will remain untested if not implemented. 
We should change the test in order to check all symbols defined within the class. This could be used by every extension.

**Comment by PeterTh** [comment]
Tests should be for all extensions.

**Comment by HerbertJordan** [comment]
There was a test for lang-basic which was verifying the proper implementation of all derived operators. Maybe this could be reused/extended?

**Comment by klois** [comment]
Is this test still there? Which one would that be?

**Comment by LuisAyuso** [comment]
Yes, that is the idea, to check each construct for parsing/sema errors. 
The difference is that lang-basic is defined in a x-macro file, which can be included by a test.cc file and expand the macros with the appropriate testing. 
The problem with the extensions is that the constructs are defined as macros inside of the class definition. This means no x-macro file, and therefore no way to include using the lang-basic system (or at least that is what I believe).
Now that you see the issue, im pretty sure you will come out with a good solution @klois

**Comment by peterz-dps** [comment]
As I faced a similar issue lately I can assist you with that...

**Comment by HerbertJordan** [comment]
The easiest is probably to add something similar to 
https://github.com/insieme/insieme/blob/master/code/core/include/insieme/core/lang/extension.h#L124
to all language extensions to get a list of all contained constructs and use this function to conduct the testing.

**Comment by klois** [comment]
I agree. I already looked into it. ir++_extensions don't appear in that list as they don't have a name. @peterz-dps proposed that all extension should have names, maybe generated from the NAME argument of the LANG_EXT_DERIVED macro.

**Comment by LuisAyuso** [comment]
:+1:

**Comment by HerbertJordan** [comment]
You could just add e.g. a whitespace in front or at the end of those who have no explicit name and then use the name form the macro. This way you could add them to the list for testing yet make it impossible to get name collisions within the parser.

**Comment by klois** [comment]
Testing for all extensions which have a testcase in core::utils as well as all which are registered in https://github.com/insieme/insieme/blob/master/code/core/include/insieme/core/lang/extension_registry.h is done with https://github.com/insieme/insieme/commit/13aa0c3979b60525ba538a1123e8571d8c698cbe
Names are currently the IR_NAME converted from camelcase to underscores without any name mangling. Do you think mangling is necessary?

**Comment by LuisAyuso** [comment]
It seems that the changes are stable, whenever we need mangling or not, can be fixed in another ticket.
:+1:
