### ISSUE TITLE
Remove if stmt after for-loop

### ISSUE THREAD

**Issue by 0ife** [insieme/insieme#43]
Right now, for-loops are followed by an if in case the loop variable is visible outside the for-loop. This behaviour is suboptimal for various reasons, esp the polyhedral model. The relevant code is in loop_analyzer.cpp l197ff.

Current implementation:

    if( (end - beg) % step == 0 )
        tmpEndValue = end;
    else
        tmpEndValue = end + (step - (end-beg) % step)

This is unnessarily verbose, the following formula is much shorter and does not use an if:

    tmpEndValue = end + ((beg-end) % step + step) % step

The double modulo is unfortunately required as the C implementation returns a negative value for negative input values. NB: There are no negative step sizes allowed in INSPIRE, so we are always allowed to use (x+step) % step, as step will be positive.

**Comment by PeterTh** [comment]
The current FE does not generate for loops at all if the loop variable is used afterwards (and if not, there is no post-processing introduced).
