### ISSUE TITLE
ut_fe_while_to_for_extension_test disabled tests

### ISSUE THREAD

**Issue by LuisAyuso** [insieme/insieme#44]
is this a desirable execution?  
the file contains tests not executed.

`[==========] Running 3 tests from 1 test case.`
`[----------] Global test environment set-up.`
`[----------] 3 tests from WhileToFor`
`[ RUN      ] WhileToFor.Simple`
`[       OK ] WhileToFor.Simple (44 ms)`
`[ RUN      ] WhileToFor.MultipleAss`
`[       OK ] WhileToFor.MultipleAss (72 ms)`
`[ RUN      ] WhileToFor.Nested`
`[       OK ] WhileToFor.Nested (45 ms)`
`[----------] 3 tests from WhileToFor (161 ms total)`

`[----------] Global test environment tear-down`
`[==========] 3 tests from 1 test case ran. (161 ms total)`
`[  PASSED  ] 3 tests.`
**`YOU HAVE 3 DISABLED TESTS`**

**Comment by stefanmoosbrugger** [comment]
I have seen this thing in several other tests...

**Comment by philippgs** [comment]
enabled in be975188ae7515ac60b24cf6942441550274fc3e
