### ISSUE TITLE
rename cmd line option --dump-trg

### ISSUE THREAD

**Issue by 0ife** [insieme/insieme#50]
I just witnessed first-hand that the name "trg" is not intuitive at all. This holds for the command line option --dump-trg as well as for the file name for temporary files.

Another naming would be very much appreciated.

**Comment by klois** [comment]
I agree. I would have never guessed that the output source file would be called trg.

**Comment by philippgs** [comment]
Sure, we can change this. But what "temporary files"? If you're referring to `a.*`, this is simply adhering to gcc's default of naming the output file `a.out`. But feel free to propose a different scheme.

The output code is usually called "target code" and the flag `--dump-trg` for historical reasons, but of course we can change that as well.

**Comment by 0ife** [comment]
I was referring to the temporary file templates [trg](https://github.com/insieme/insieme/blob/master/code/utils/src/compiler/compiler.cpp#L224) and [src](https://github.com/insieme/insieme/blob/master/code/utils/src/compiler/compiler.cpp#L235).
