### ISSUE TITLE
Cleanup of node replacer modification

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#55]
The processing for issue #25 altered the interface for the [replacement utilities](https://github.com/insieme/insieme/blob/master/code/core/include/insieme/core/transform/node_replacer.h). This needs some cleanup.

The parameter name *skip* is misleading in the sense that it is not only skipping selected nodes but the entire associated sub-tree. It is more adequately referred to as prune than as skip.

Furthermore, essentially the limit scope flag and the *skip* predicate are serving the same role. There should be a single parameters called *limit* of a type *ReplacementLimit* offering options like *global*, *local* and manual overloads.

Possible implementation:
```C++
typedef std::function<bool(const NodePtr&)> ReplacementLimit;
struct Global : public AcceptAll<const NodePtr&> {}
struct Local { 
      bool operator(const NodePtr& cur) const { return cur.isa<LambdaExprPtr>(); } 
}
```
Manual boundaries may then be passed by a lambda as required.

**Comment by PeterTh** [comment]
Yes, we already discussed this on Friday. I'd like to add that it should probably be possible to either prune **or** skip, since both are distinct cases and both are useful.

This could e.g. be implemented by having the lambda/std::function not return a bool but a (class) enum like { Process, Skip, Prune }.

**Comment by HerbertJordan** [comment]
Yes, good idea.

**Comment by PeterTh** [comment]
Actually { Process, Skip, Prune, Interrupt }.

**Comment by PeterTh** [comment]
Completed in https://github.com/insieme/insieme/commit/f6cce5c9a2df4d3c9285bd0dc85fa514178bf0e0.

Note that this commit removes almost 200 lines despite increasing the available functionality. Looking through those files, I'm sure that a more thorough refactoring could result in at least another 500 redundant lines.

Also, we really need to take DRY more seriously. There was another subtle bug in the replacement stuff related to features/changes being propagated only through half the slightly different repetitions of the same concept.
