### ISSUE TITLE
Should we get rid of StmtWrapper in the frontend?

### ISSUE THREAD

**Issue by philippgs** [insieme/insieme#56]
I started fixing the test pragma handling which at some point must have supported calling handlers for pragmas attached to types because there are unit tests covering that. However, the new PragmaHandler only supports calling handlers for pragmas with `StatementList` as targets, hence the unit tests fail. While checking this, I noticed that the frontend actually uses `StmtWrapper`, which is a tiny wrapper class of `StmtList` (see https://github.com/insieme/insieme/blob/master/code/frontend/include/insieme/frontend/utils/stmt_wrapper.h#L57-L83).

AFAIK pragma handling needs to be changed to deal with `NodeList` instead of a `StmtWrapper`, however shouldn't we get rid of `StmtWrapper` alltogether, and consider moving `tryAggregateStmt()`, `tryAggregateStmts()`, `makeOperation()` to `insieme::core::utils` if they are heavily used?

I think it is quite some manual effort, refactoring-wise, but I don't see the point of `StmtWrapper`. Also already suggested by @PeterTh.

**Comment by PeterTh** [comment]
Actually, I suggested removing `StmtWrapper` when I was under the impression that it's merely another name for `StmtList` (that is, a `vector<StmtPtr>`). The fact that it isn't (any more?) makes the decision a bit more involved since it increases the effort for something which doesn't really have a huge payoff.

**Comment by philippgs** [comment]
Exactly, hence the open question! It would make the code slimmer, but there are over 100 occurrences of `StmtWrapper` in the frontend.

IMHO we could probably also just change `PragmaHandler` to deal also with arbitrary nodes, with some appropriate casting before/afterwards.

**Comment by PeterTh** [comment]
I'll close this as "no" for now.
