### ISSUE TITLE
Cleanup build process by removing own GCC dependencies

### ISSUE THREAD

**Issue by HerbertJordan** [insieme/insieme#57]
I'm not completely sure, but I think we finally got to the point where we can abandon our GCC and ruby builds in the lib directory (or make it a opt-in option) and use the system compiler. The C++11 standard should be widely enough spread already, now that actually its successor is already out.

The reason for this: our README front page for the project is very complex, in particular the part with the LD_LIBRARY_PATHS is anoyingly complex; this could help to eliminate this obstacle for future users.

**Comment by philippgs** [comment]
I agree. The current CMake refactoring work of @berhoeckner already assumes that these custom builds are only an opt-in option, as they are not required by default and system-provided libraries and tools will suffice if they match the version requirements.

**Comment by peterz-dps** [comment]
This should have been fixed largely by the work of @berhoeckner with his latest commits.

Now cmake will use whatever software it can find in XXX_ROOT, INSIEME_LIBS_HOME and the system default in that order and also warn on version mismatches.

Basically there probably isn't much software left we need to compile ourselves to compile insieme.
