### ISSUE TITLE
Regression:  Aos to Taos  

### ISSUE THREAD

**Issue by LuisAyuso** [insieme/insieme#58]
New inspire parser breaks Tuple test in the following test file:
https://github.com/insieme/insieme/blob/master/code/transform/test/datalayout/aos_to_taos_test.cc

The test has being commend until fix. @klois any idea?

**Comment by klois** [comment]
No, I don't know so far. Probably ur parser is generating something a bit different than the old one did.

**Comment by klois** [comment]
Fixed with https://github.com/insieme/insieme/commit/de6a13644be470bc7b686deef9da3cc26a3f7097
