### ISSUE TITLE
Several insiemecc issues

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#59]
1.) GCC supports multiple definitions of the std flag:
E.g.: ```g++ --std=c++11 file1.cpp --std=c++03 ...```
How should we handle this? Currently we solved this
by using the first definition of the std flag but I don't know
if this is the correct way. Is it possible to set different standards
for different input files (in one compiler call)?!

2.) No support for ```-x``` flag. This flag is implement now, but what 
happens if you write something like ```gcc input.c -x c++ --std=c99```.
This is somehow conflicting, right?!

3.) Using insiemecc in CXX or CC is not that good. We are using this
variables as backend compiler information. This leads to recursive
insiemecc calls (e.g., using CXX=insiemecc with cmake).
I would propose to use an environment variable (e.g., INSIEME_CXX)
that stores the path to the used backend compiler. Maybe with a fallback 
to gcc or so.

**Comment by stefanmoosbrugger** [comment]
1 and 2 is fixed with https://github.com/insieme/insieme/commit/bdf71384f396267c6a5ba067e97c1b832b9dc388

**Comment by philippgs** [comment]
3 is fixed with 94e3e662d861e8a6cd0a3a7d1f43e72537069344, the environment variables are called INSIEME_CXX_COMPILER and INSIEME_C_COMPILER, respectively. Fallback is currently g++/gcc.
