### ISSUE TITLE
Possible name collisions in special character handling in IR naming

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#60]
There is a bug in the Insieme frontend 
renaming conventions. It is very easy
to produce name collisions.

Simple example input code:
```
namespace MPI {
 class Status {
    ...
 };
}

struct MPI_Status {
...
};

int main() {
 MPI_Status element;
 MPI::Status another_element;
}
```

This will lead to a name collision because the MPI::Status 
class will be renamed to MPI_Status. Unfortunately there is already
a struct called MPI_Status. We have to think about the renaming 
convetions. For the list of renaming conventions see https://github.com/insieme/insieme/blob/master/code/frontend/src/utils/name_manager.cpp#L65-L81.

**Comment by PeterTh** [comment]
Actually, I think doing a simple string replacement as it is done currently is probably always going to be insufficient. We probably need more semantic information to generate the name, e.g. something like __ns_MPI_Status in the example.

For now you could probably simply replace "::" with "_scope_" or something like that to eliminate 99% of all collisions.

**Comment by stefanmoosbrugger** [comment]
yep.. i solved it currently with the ```__ns_``` approach. But there 
are plenty of other possibilities to generate name collisions.
So I guess we should find a better solution for naming problems..

**Comment by HerbertJordan** [comment]
Could we simply use `::` in the type name?

**Comment by stefanmoosbrugger** [comment]
I will try this out. But as far as i know this is not working. We should think about a solution for this problem when solving the issues mentioned in https://github.com/insieme/insieme/issues/61.

**Comment by LuisAyuso** [comment]
I agree with @HerbertJordan  on the simplicity of the name.
On the other hand, names with symbols can not be used in the backend since the namespace might no exist. 
This is a tricky problem since the name is the only way to associate overloads (as seen in #61), and differentiate functions with equal name and different cv qualification.

**Comment by PeterTh** [comment]
This is no longer an issue in the new frontend, with unified name mangling/demangling.
