### ISSUE TITLE
conflicting SIGUSR1 handler usage between mpich2 and insieme runtime

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#62]
When trying to start an executable that is using the insieme runtime with mpirun
it may happen (at least for mpich2) that the application cannot be launched. The
reason for this is that the SIGUSR1 handler is already reserved by the insieme runtime.
Unfortunately the mpich2 wants to make use of the SIGUSR1 signal handler.
Any ideas how this should be solved?

**Comment by peterz-dps** [comment]
This is probably a non-issue, as MPICH is **ancient** by now. I'll investigate...

**Comment by PeterTh** [comment]
We could (optionally) use e.g. SIGRTMIN and SIGRTMIN+1 for the runtime signals, instead of SIGUSR1 and SIGUSR2. (see https://github.com/insieme/insieme/blob/master/code/runtime/include/error_handling.h#L52-L53)

**Comment by peterz-dps** [comment]
The first release of version 2 of the MPI standard was released back in 1997. As MPICH is (and to my knowledge always has been) the reference implementation of the standard it will probably have been released at that time also for the first time. However - the last MPICH2 release probably dates back only to 2012 - just before the first release of version 3.

As @stefanmoosbrugger already solved the problem now by using my version 3.0.4 this isn't an issue anymore currently.

On the other hand, when he told me about this problem my first reaction was, that basically MPICH mustn't really make any assumptions about the handling of these signals in the user program - the program should work whether or not it uses these signals.
However, the same reasoning can/should be applied to Insieme also. If user code used these signal handlers somehow we should at least think about supporting this somehow...

**Comment by PeterTh** [comment]
How? The signalling mechanism is inherently non-composable.

Well ... we could check if there are two RT signals available, and if so, use those and redefine SIGRTMIN as OLD_SIGRTMIN+2.

**Comment by PeterTh** [comment]
Fixed in https://github.com/insieme/insieme/commit/ef9cc722f68ee1eae33dad38d239dbfa7fdfaf98 (with a sledgehammer, the runtime no longer uses any custom signals).
