### ISSUE TITLE
Support wildcards in ExcludeSteps

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#65]
Writing ExcludeSteps clauses for integration tests is much more annoying than it should be.
Just supporting a * wildcard would make it much easier (and config files a lot more readable).

**Comment by peterz-dps** [comment]
This has been closed by commit 04c37a4729905600d985bcab08970d22bf215d80 and refined by commit 07c96df864a0c4ec8d93380c17b4ad225f962578
