### ISSUE TITLE
Add ref qualifiers to methods returning references

### ISSUE THREAD

**Issue by 0ife** [insieme/insieme#66]
As discussed today, returning references to fields should be allowed only when we let the compiler know our intentions by marking up the source with the proper **lvalue/rvalue ref qualifiers**, as introduced in [C++11](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2439.htm). For examples, see [stackoverflow](http://stackoverflow.com/a/8610728) and the example below. That way, we can be sure that temporary objects are not destroyed before their members are being used.

Example:

    MyFieldType& MyObj::MyMeth() & { ...; return &myfield; }

instead of

    MyFieldType& MyObj::MyMeth()   { ...; return &myfield; }

This ticket was triggered by the following code: https://github.com/insieme/insieme/blob/master/code/transform/include/insieme/transform/transformation.h#L272

This change will bump the **minimum GCC version to [4.8.1](https://gcc.gnu.org/projects/cxx0x.html)** in case we need to use any rvalue ref qualifiers.

**Comment by LuisAyuso** [comment]
I would not say that this is severe.
Of course tools could be a little more robust, but in the end this is just an issue that can be solved with a little of common sense. The validity of our solution is not compromised.

**Comment by PeterTh** [comment]
It's also not a bug, actually.

**Comment by LuisAyuso** [comment]
:+1:

**Comment by PeterTh** [comment]
Preliminary decision: drop 4.7.

**Comment by PeterTh** [comment]
We have dropped 4.7, and some core methods now exist in ref qualified and rref qualified form.
