### ISSUE TITLE
node replacer mistakenly instantiates LANG_EXT_LITERALs

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#69]
There is a problem when using enumerations in ocl host or kernels source files.
The backend addon that handles the IR to C translation of enum types and operators
was not installed when using the ocl_hst or ocl_kernel backend converter. The fix is pretty
easy. Just add the enum_type_addon to the list of instantiated backend addons in 
https://github.com/insieme/insieme/blob/master/code/backend/src/ocl_host/host_backend.cpp#L90-L98 and https://github.com/insieme/insieme/blob/master/code/backend/src/ocl_kernel/kernel_backend.cpp#L75-L81. 
No sooner said than done! 

But there are still problems:
The type of enumerations is translated back into C code like it should be 
but the enum operators (e.g., enum_to_uint) are not translated. 
I discovered that the backend operator converter table contains the information
that is added when installing the enum addon but unfortunately the callExpr converter
in the backend cannot find the entry in the table (see https://github.com/insieme/insieme/blob/master/code/backend/src/function_manager.cpp#L381-L395). Just to give an example how the variables and arguments look like when FunctionManager::getCall is called:
```
## dumpDetail(fun) when using one of the ocl backend converters ##
$[-shared node-: enum_to_uint:$[VariableInstantionInfo: ($[Value(N7insieme4core11annotations7NameTagE): __insieme_enum<_enum_name,__insieme_enum_constant__<_enumCtnt_Linear,0>>]$) -> uint<4>]$($[-shared node-: _enumCtnt_Linear:$[Value(N7insieme4core11annotations7NameTagE): __insieme_enum<_enum_Kind,__insieme_enum_constant__<_enumCtnt_Linear,0>>]$]$)]$

## dumpDetail(fun) when using standard backend converter ##
$[-shared node-: enum_to_uint:('a) -> uint<4>($[file.cpp@19:19-19:30: (( *$[file.cpp@19:19-19:28: ($[file.cpp@19:19: ( *$[file.cpp@19:19, Value(N7insieme4core11annotations7NameTagE): v2]$)]$&[0u:uint<4>])]$).type:identifier)]$)]$

## operator table entry ##
enum_to_uint:('a) -> uint<4>
```

**Comment by stefanmoosbrugger** [comment]
Ok, after a little bit of investigation we discovered that this is not a backend bug. The
problem is located in the node_replacer. As you can see in the example of the first comment 
we can see that the derived literal called enum_to_uint is instantiated and therefore not found
in the operator table anymore. 

Lets say we have a piece of code that contains a call to ```enum_to_uint``` (which is a LANG_EXT_LITERAL). And now we call the ```NodeReplacer::fixTypes``` method (this is for example done in the ocl frontend extension) that can be seen in https://github.com/insieme/insieme/blob/master/code/core/src/transform/node_replacer.cpp#L1438-L1443. Lets say we have no replacements and use the default type handler as arguments. The ```TypeFixer``` node mapper will be called and this leads me to my first question:

*Can we do an early exit in the type fixer or any other node replacer if we know that we do not have any replacements?!*

But anyway. Basically it should not be a problem (except performance issues) if we visit all the nodes even if there are no replacements. The actual problem is that the ```TypeFixer``` is instantiating and replacing all LANG_EXT_LITERALs because they are not identified as built ins. As a result in our example we get a piece of code that still contains the  ```enum_to_uint```, but now the function type is not ```('a) -> uint<4>``` anymore. Now it is something like ```insieme_enum<...> -> uint<4>```. And this will not be identified as an operator in the backend anymore.

One way to fix this would be to check if the node is a LANG_EXT_LITERAL. If yes, handle them like it is a (real) builtin. Anybody knows problems that can occur when doing this?!

**Comment by stefanmoosbrugger** [comment]
closed with https://github.com/insieme/insieme/commit/b95ef6c1b0a5613cc65c9421168edfd3f1eca0e8

**Comment by HerbertJordan** [comment]
The solution is very bad performance wise. To check whether a construct is somewhere in a language extension it is in the worst case instantiating all known language extensions, which -- if i remember correctly -- triggers the parsing of the definition of all their constructs -- and checks whether it is present. And this worst case is the case where it is not really a construct in some of the extensions. 

A much more efficient solution, that als does not depend on the central extension registry, would be something similar to the [isDerived](https://github.com/insieme/insieme/blob/master/code/core/src/lang/lang.cpp#L75-L77) check. Every extension is adding a simple annotation tagging its defined constructs. Then you simply have to check for that tag -- quick and simple.

Basically

**Comment by PeterTh** [comment]
Heh, that's pretty much exactly what I told Stefan last week.

**Comment by stefanmoosbrugger** [comment]
jep, i remember. i will work on this next week..

**Comment by stefanmoosbrugger** [comment]
commit https://github.com/insieme/insieme/commit/fd4c781be5ecb894013a0dd1f78f27017d7f0cc4 should fix the performance issue.
