### ISSUE TITLE
 Fix handling of multi-dimensional variable-sized arrays

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#7]
int n;
int a[n][n];
int x = a[1][2];

**Comment by LuisAyuso** [comment]
@philippgs  You do have an snippet for this issue, don't you?

**Comment by PeterTh** [comment]
@LuisAyuso @philippgs lunch was nice wasn't it?

**Comment by philippgs** [comment]
An MWE is:

```c
int main(int argc, char** argv) {
    int A[argc+5][argc+5];
    int x = A[5][5];
}
```
which results in the output code (sequential backend, but runtime backend generates the same):
```c
int32_t main(int32_t argc, char** argv) {
    int32_t* A[(uint64_t)(argc + 5)];
    int32_t x = (&A[5u])[5u];
    return 0;
}
```

I think it's the frontend, since we seem to get `decl ref<array<array<int<4>,1>,1>> v3 =  var(array.create.1D(type<array<int<4>,1>>, v1+5));` and `decl ref<int<4>> v54 =  var( *v3&[5u]&[5u]);`

**Comment by LuisAyuso** [comment]
@0ife 
Upgrade:
Multi dimensional arrays where never implemented in Backend.
At this point, it will make sense to consider the need to keep separate IR tools for 1 dimensional arrays.
I propose:
 - Define pointer type, and avoid use of array<t, 1> for this proposes
 - Remove Array<1> operators or turn them into derived based on Array<n>
 - of course, implement array<n> operations in Backend.
 - fix everything that will break because of this.

**Comment by HerbertJordan** [comment]
I'd say the detour via the pointers is a messy endeavour which will lead to a dark place nobody wants to go to. Proper supporting for multi-dimensional arrays in the backend should be rather simple and I'd recommend to just go for it and use the corresponding IR constructs in the frontend to encode the given use case.

**Comment by LuisAyuso** [comment]
Why pointers are a detour? 
what is an endeavour?
what dark place?  
what IR to use then? makes any sense to keep Array 1D and Array ND?

**Comment by LuisAyuso** [comment]
Again: is the backend the one not implementing ND_array operations.
I will not start doing exceptions in fronted and backend to handle cases for 1D and ND arrays, they need to be unified. I am not touching the Array and Array related operator until pointers take care of their duty. 
If is not time for pointers to come, then we freeze this ticket until they do.

**Comment by HerbertJordan** [comment]
ok ... i will refrain from the future use of metaphors and write a post
making it more clear ...

**Comment by HerbertJordan** [comment]
To state it clearly: no, the backend is not supporting multi-dimensional arrays yet. But I think fixing this should be integrated -- which shouldn't be hard.

Also: i think the proper support for pointers and pointer arithmetic and this issue with the arrays are two orthogonal issues. Those should be added one after another to not cause too big modifications which might cause a broken state for a too long time.

The thing about the multi-dimensional arrays is: the multi-dimensional version is the unified default you are asking for. The 1D array that is used everywhere is the actual special case. Each array access actually receive a vector of coordinates (one for each dimension). Correspondingly in the 1D case this vector is of length 1 and for convenience we have skipped the vector and just utilized the index.

So we could get rid of all the distinction of 1D / ND by simply utilizing the ND signatures everywhere and no special cases need to be handled in the frontend (Step 1). Once it is running for all codes so far -- those codes only using 1-dimensional arrays, we add support for 2 and higher dimensional arrays in the backend (Step 2) and final in the frontend (Step 3). Does this sound like a plan?

Later on, when this is working, we replace the pointer handling that is currently based on ref-array combinations by the proposed reference/offset model -- assuming this is the concept you are referring to?

**Comment by LuisAyuso** [comment]
I somehow get the feeling that is useless work for such an small feature.
The right thing to do is to fix the ND arrays, but i would not start with that until the pointers stop making use of the array type, that is the reason of my order of tasks.

**Comment by HerbertJordan** [comment]
The value is indeed very little. Up until 2h ago I actually thought there are no multi-dimensional arrays in C and that the given code example is actually illegal. Then i tried it ... shit is really working. And the craziest thing: when you use the sizeof operator on those dynamic, multi-dimensional arrays ...

@philippgs is there an urgent use case?

**Comment by LuisAyuso** [comment]
this feature is for @0ife and the polihedral model.
Yeap, I'm afraid that the compiler does the right offsetting without using intermediate index arrays.
Implementing a workaround in INSPIRE might turn into a performance killer... we should not do it half way.

**Comment by LuisAyuso** [comment]
Bonus: you can mix variant array sizes with constants, this turns into array<vector<array<T,n>,m>,k> in ir... maybe it should just be array<T, 3> var = ND_array_create( ...  (n,m,k) ... )

**Comment by HerbertJordan** [comment]
Ok ... stupid question - who is @0ife ? Thomas P?

And: for this use case, can't it be manually turned into a constant or something and we use nested vectors? 

Doing it properly with the necessary backend support would for me be the way to go, but if it can be circumvented it saves the effort.

If possible we identify the creation of those Arrays in the frontend and report an error that this is an unsupported feature and the code should be re-written to something static ...

**Comment by philippgs** [comment]
Yes, @0ife is TP. And this construct appeared in a math solver coming from the PolyBench suite.

**Comment by 0ife** [comment]
**@HerbertJordan:** what do you mean with "To state it clearly: no, the backend is not supporting multi-dimensional arrays yet. But I think fixing this should be integrated -- which shouldn't be hard." — Can you elaborate what (easy) solution you have in mind?

**On pointers in C:** I am of the opinion that in C (at least) pointers and arrays should not be viewed independently; the reason is that a[5] and 5[a] are both perfectly legal and refer to the same memory address. However, and this we must not forget, we want to create an IR that is not only suited for C but one that is more versatile. So, in this light it would make sense to see pointers and arrays as two different things: Arrays you should be able to reason about, pointers do not have this advantage in the general case.

**Comment by HerbertJordan** [comment]
What I meant to say is that the lack of multi-dimensional array support in our compiler does not stem from a lack of IR constructs. There it is pretty clear how to encode those (with the exception of dynamically sized array for which C is tracing their size). The code generator in the backend is just not capable of creating code for those yet. And the point is: don't try finding an encoding in the IR using supported construct to circumvent this shortcoming of the backend -- fix the backend.

The (easy) solution I have in mind is: provide general support for arbitrary-dimensional arrays in the backend. This might or might not require runtime support -- depending on the implementation. But propery done it should not cause any performance impact. After all, a C compiler has to face the same issues and we can just re-build their solution -- ideally by simply utilizing the corresponding C constructs.

**Comment by HerbertJordan** [comment]
On the pointer vs. array issue: this is syntactic sugar. The fact that a[5] is the same as 5[a] -- those are C details we do not have to preserve in the IR and we/I would actually prefer to get rid of. 

I'd guess that pointer and array analysis are essentially in the same complexity domain. One problem can be translated into another (array => ptr ... the way C does it, ptr => array ... by assuming a huge array representing the main memory and considering pointers indices on this array). So i guess they are equivalent.

What we have in the IR is the distinction between *references* (=utility for managing mutable memory), *arrays* (=data construct for homogeneous list of data elements of dynamically determined size) and *vectors* (=data construct for homogeneous list of data elements of statically determined size). So in our IR arrays have nothing to do with memory allocation -- they might not even be stored in memory (by having an address).

**Comment by LuisAyuso** [comment]
Yes, I agree with you guys. 
Pointers should be arrays and vice-verse.
Could you please continue this discussion in the array thread #42 ?

**Comment by PeterTh** [comment]
On a curious side note related to this issue -- I just read while looking for something unrelated that [here](https://parasol.tamu.edu/people/bs/622-GP/C++14TAMU.pdf) Bjarne Stroustrup has this to say
> C99 VLAs is an abomination – Just look at a “pointer to VLA”

between this and them being removed again from being a mandatory part of the standard in C11 I think this could inform us on how exactly we want to adapt or model VLA semantics in INSPIRE.

**Comment by PeterTh** [comment]
I think this issue is subsumed by https://github.com/insieme/insieme/issues/42.
