### ISSUE TITLE
Test pragma and unit tests not functional, pragma handling needs to be reworked

### ISSUE THREAD

**Issue by philippgs** [insieme/insieme#71]
Currently, the pragma

    #pragma test "expected_ir_construct(s)"

and the unit tests using it (type conversion, type casting, pragma matcher, ocl platform types, and stmt conversion) do not work. The unit tests fail to register the pragma handler for this pragma, but also only perform checks on pragmas that are found. Since none are present due to the missing registration, the tests erroneously succeed without doing any work. I did not want to fix the unit tests yet, since they break because the argument string of the pragma is not saved. As a result, the unit tests would all (correctly) fail, and I want to fix everything.

Related to #70.

**Comment by PeterTh** [comment]
Github not as smart as you thought!
