### ISSUE TITLE
ocl integration tests create a lot of useless files

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#72]
Why is the preprocessing step in the ocl integration tests generating a lot of symbolic links?!
The mock run of the preprocessing step shows the following output
```
preprocessing
cd insieme_dir/test/ocl/convolution && 
LD_LIBRARY_PATH=./:${LD_LIBRARY_PATH} bash -c "gcc -std=c99 -Wall -fPIC -c ../common/*.c -I../../../code/frontend/test/inputs -lOpenCL -lrt -O3 -D_GNU_SOURCE=1 && 
gcc -shared -Wl,-soname,libicl.so.1 -o libicl.so.1.0 *.o && 
ln -sf libicl.so.1.0 libicl.so && ln -sf libicl.so.1.0 libicl.so.1 && 
rm ./*.o"
```
Either there should be a cleanup step or something else that is 
removing this files after the integration test finished.

**Comment by PeterTh** [comment]
I think the links should be deleted in the postprocessing step

**Comment by stefanmoosbrugger** [comment]
Done... Added a post-processing step that deletes the files.
