### ISSUE TITLE
Pattern match lambda 

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#8]
Extend pattern matcher with pattern that evaluates a lambda to check for match.

**Comment by HerbertJordan** [comment]
Can you provide an example?

Do you want to have a lambda on tree patterns, list patterns or checked by rules after a certain pattern has been discovered?

**Comment by PeterTh** [comment]
The idea is to have a tree (or list) pattern which takes a lambda of type NodePtr -> bool indicating whether it matches a node.

**Comment by klois** [comment]
Can we also make a lambda that takes NodeAddress as an argument?

**Comment by HerbertJordan** [comment]
Sure, should be doable.

**Comment by PeterTh** [comment]
Completed in https://github.com/insieme/insieme/commit/c1f9a0ec4719e1c352e02b6a76dd6166890fa163
