### ISSUE TITLE
About Type qualification.  

### ISSUE THREAD

**Issue by LuisAyuso** [insieme/insieme#83]
**Note:** *This post applies to C inputs, C++ need to extend this a little*

Recently I have talked about volatiles and the way they were model (#81).

Thinking about the best way to fix this and model any kind of type qualification I came to the idea I want to discuss here: 

In C,there are 3 qualifiers for any type: **const**, **volatile** and **restricted** ( plus 1 more **_Atomic** in C11)
The standard states: *The properties associated with qualified types are meaningful only for expressions that are lvalues*  
Left sides are mutable locations and therefore are translated as ```ref``` in IR. 
It makes sense to think in something that looks like:

C type | Rside value | Lside value
------------ | ------------- | ---------------
```T``` | ```T'``` |  ```ref<T'>```
```const T``` | ```T'``` |  ```src<T'>```
A const Left side is a kind of reference type (source)  since the standard says: *The implementation may place a const object that is not volatile in a read-only region of storage*. But it could be just a alue as well. 

The list continues like: 

C type | Rside value | Lside value
------------ | ------------- | ---------------
```volatile T``` | ```T'``` |  ```volatile_ref<T'>```
```_Atomic T``` | ```T'``` |  ```atomic_ref<T'>```

(note:  I leave restricted for another iteration since it only applies to pointers) 

At this point we could assume that qualifiers are only needed at reference types, and this is true. But there are a couple of places that can hold qualifiers in C and the corresponding IR will hold no reference:

- ``` void fun (volatile a) ``` will turn into ``` fun( int<4> a) -> unit ``` 
   To preserve the program semantics, the volatile needs to be applied to the materialization of the read-only parameter whenever it is used by reference inside of the function body: 
``` 
fun(<int4> a) -> unit { 
    decl volatile_ref<int<4>> v0 = var(a);
    // use v0 by value .....
} 
```
- ``` struct { volatile x; } ``` will turn into ``` struct { int<4> x; } ```  as a right side and ```ref<struct { int<4> x; }> ``` as left.
    In this case the volatile appears when creatin g a member access:
``` v->x ``` of type ``` volatile_ref<int<4>> ``` 

The main problem is that we need a mechanism to propagate the qualification of types with the types even in those scenarios where the type does not exhibit the properties (i.e. because is used as a rside).
The current solution models this right, int<4> turns to be volatile<int<4>>. But needs a lot of operations to unwrap and wrap the expressions every time the type is used by value. Nevertheless, no semantics are model in the left side, which is typed   ``` ref<volatile<T>> ``` and the volatile/atomic semantics are mostly ignored.
I propose a different solution: **Type Tagging**:
As in C, every type can be tagged with the qualifiers. This does not alter the operation with this type but the tags are guaranteed to stay with it along its usage. The tags will be used in certain scenarios: 
- builder.refType( .. ): When generating a ref type out of a type T, the ref generated will be of the appropriate kind.
- memberRefAccess: the result of this function needs to be coherent with the qualification of the field.
- RefDeref: this returns a Rvalue in any case
- Operators: Every operator needs to provide the appropriate interface, and are these new operators the ones that really model the usage of the Qualification: (i.e. Atomic increment with an atomic variable) 
- a few others that might pop out here and there.... 

This alters a little the design of our IR, but I think it would be a robust solution.

The qualified ref types can be replaced by more sophisticated types to have a finer control of the data flow. But they should be keep the interface with the operations, much smarted tools need to be implemented in the builder, with one entry point, instead of delegating the selection of the right operator to the IR user (whoever writes fronted/transformations) : 
I.e: builder.refType (T) should return:
   ``` ref<T> ``` for unqualified
   ``` atomic_ref<T> ```` for _Atomic T ( or ``` channel<ref<T>> ``` or ```atomicMagicType<T> ``` )
This way, any tool ever build will create the right types.

**Combination**
I could not find any use where the combination of the qualifiers is useful... but maybe should be modelled. For _Atomic the standard drops says: *If other qualifiers appear along with the _Atomic qualifier in a specifier-qualifier-list, the resulting type is the so-qualified atomic type*

**In the Backend**
The translation back to C is easy. Only the variables declared to have a qualified reference type need to qualified in the output code. Any qualification stored in types is dropped, with the exception of qualification in member fields. Parameters with qualifiers appear unqualified in the produced code, it is the variable in the body the one which exhibits qualification. 

**About Pointers and Arrays**
The outgoing pointer type is compliant with this post.

**Comment by HerbertJordan** [comment]
I think this goes in the right direction. We can modify the IR type system if we need it to model the corresponding behaviour. And this point should be added to #29.

On a small Detail: I'm not sure whether we should make the IR core builder 'smarter' by specializing it more and more to the needs of the C/C++ frontend -- although it is, and will be for the forseeable future, our only frontend. The builder should probably be split appart like the language extensions and language specific operations should be moved to the frontend.

What we would need:
* a grammar of our new type system (an extension / modification of the current one)
* a semantic specification for those type constructs
* a description of abstract types + operators to model the necessary operations
* a semantic specification for those abstract operators
* a verification that we can accurately model the semantic of our processed codes

The last step may be covered in a less formal way (since its correct handling would require a formal definition of our input languages and such a thing does not exist).

Besides that, one other important question needs to be covered: How to we justify this effort? Is there some research result we can obtain or is it a absolute requirement for upcoming projects?

Any comments on that?

**Comment by HerbertJordan** [comment]
This might also be connected to handling C++ references.

Or maybe we throw away the language independent nature of our IR and start building an actual C/C++ IR.

**Comment by LuisAyuso** [comment]
I somehow agree with the idea that IR should be model more accurately the semantics of C. But I also believe in the independence of the IR. 
One of the main problems we run into nowadays is that there are constructs in C that need to be translated into IR where the semantics of them are different. (i.e. arrays by reference in C arrays by value in IR). There are several operations to provide the means to convert and use the types that currently are implemented as Literals and it is not unusual to find special handlers for those operations inside of analyses.

I would provide IR with a finer grain and more abstract set of operations that allows us to implement derived operators for every C construct: Get closer to functional programming. 
Using fold operations and introducing a list type (or upgrading the current one) would give us the means to implement derived operations for all collective types. Independently of passing y reference or value. 

I'm really looking forward for some blackboard time...

**Comment by HerbertJordan** [comment]
Blackboard time you want, blackboard time is what you get!! :)

**Comment by PeterTh** [comment]
Type qualification on references is explicit in inspire 2.0
