### ISSUE TITLE
Losing (or not considering) const qualification when casting pointers

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#89]
We do not consider the const qualification when casting a pointer to a base class. 
In some cases we have to preserve this information. Unfortunately I don't have a 
simple test case yet but the problem is something like "const method call that casts 
this pointer down to a base class and calls a non const function". 

If the cast result is non const (as it is in the target code) we will get a compiler error.
I will update this ticket as soon as I have a minimal test that reveals this error.

In the clang_cast frontend utility we can see following handling of derived to base casts:
https://github.com/insieme/insieme/blob/master/code/frontend/src/utils/clang_cast.cpp#L470-L503 

As you can see we do not even check if the target type is const qualified or not. 
The IR for a ptr cast to a base class looks like ```ref_narrow(scalar_to_array(...), (dp_root.as<type<type001>>))```

The backend is converting the ref_narrow into a static cast to the target type but 
the const information was already thrown away in the frontend. 

Any ideas how to preserve the const qualification?! 
I guess an annotation or const tag is not an option...

**Comment by PeterTh** [comment]
This seems related to https://github.com/insieme/insieme/issues/83 (that is, type qualification in general).

**Comment by PeterTh** [comment]
In the new FE and with the new explicitly qualified pointer type, this cannot happen.
