### ISSUE TITLE
Killing ClassMetaInfo

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#90]
We all know that ClassMetaInfo is an abomination unto god. And worse, unto Inspire. So, we need to kill it.

Stefan and I had a discussion today on what to do about it. Here are some basic qualities any solution should (in our opinion) have:
* **Don't store semantically relevant information in annotations.**
* Model all relevant C++ features we need to preserve.
* Require as little modification to IR semantics as possible, given the above.

The solution presented below is not to be taken as the final wisdom regarding this, but this issue should serve as a discussion platform to derive a final solution, and **sooner rather than later**. Before Stefan rewrites all our basic IR tools to also work on semantic information stored in annotations :P

So, let's go. This is our initial idea (not yet fully vetted!):
First, we need to introduce a new node type, let's call it `ClassExpr`. Unsurprisingly, a `ClassExpr` is an expression. It features
1. A NamedCompositeType, describing the class value types as usual.
2. A list of DispatchExprs modeling the methods, as per https://github.com/insieme/insieme/issues/85#issuecomment-113716798.
3. A single LambdaExpr, the destructor.

Whenever a method is called, it's done with a built-in operator wit a signature like this:
`methodcall(ClassExpr, DispatchExpr, instance)(arg0, arg1, ..., argN)`
where `methodcall(...)` returns a LambdaExpr with the right signature.

**Comment by HerbertJordan** [comment]
I agree, down with the ClassMetaInfo. But after thinking about this proposal for 3 minutes, I guess that it requires quite some additional work to prevent inconsistencies and abiguities.

For instance, the proposed DispatchExpr of #85 combines all the overloads of a function from all derived classes. In this proposal this instance would have to be kept consistent in all corresponding `ClassExpr` instances. It is thuse working a bit against the actual idea of the dispatcher expression, enabling you to lokaly define a dynamically dispatch function (like a match statement) not referencing or influencing any other section of the code.

Also, it is probably hard to find a type for the `methodcall` build-in, which means that this can only be integrated by creating a new node type for it. 

An alternative would be to allow named method implementations in struct types + support for constructors and destructors. But not directly or virtually called member functions where the call-site is within the IR. Those we handle utilizing lambdas and dispatch expressions exhibiting member function types. 

The original reason why we didn't wanted to do that was the issue that we didn't wanted to allow expressions within types. This has various problems -- and it might still be a too big problem for following this path. For instance, type identity would then be based on function implementations -- you change a variable name, you get another type. Also, we would have constanstantly to deal with recursive types with very complex to specify variable scopes. 

He have seen in the past that this is a difficult issue and it is about time to get rid of it. We need to design something that is able to cover all we need, make sure we all understand how it works, how it should be utilized, how the responsibilities are devided between FE/Core/BE, and then implement it. No more hacking, no more pressure from TF to get it fixed soon, no more panic reactions. Quality is required.

Where is this issue on the priority table? Can we pospone this until I'm back?

**Comment by PeterTh** [comment]
Yeah, one case I missed in the initial comment was e.g. A::foo calling B::bar which calls another method of A. At the very least we'd need the same (mutual) recursion solution we use for types/functions for ClassExprs, and everything which is not completely trivial would end up recursive.

As for the time table, I think we should do this before starting to implement all manner of fixes (required by new input codes) which target the symptom (bugs related to ClassMetaInfo annotations all over the compiler) rather than the cause (the very existence of ClassMetaInfo). We got to talking about it today because Stefan was about to redesign the entire visitor/mapper infrastructure to also visit/map annotations (which have child lists).

I do think another, what, month? won't matter much at this point, we've lived with this for a while now.

**Comment by HerbertJordan** [comment]
I will be back on July 16 -- and yes, i fully agree, we need to target the causes, not the symptoms.

Maybe be can work out and discuss proposals until then conceptionally.

**Comment by LuisAyuso** [comment]
:+1: 
Lets do this when you are back.

**Comment by PeterTh** [comment]
Victory.
