### ISSUE TITLE
type<X> not a subtype of type<'a>

### ISSUE THREAD

**Issue by klois** [insieme/insieme#91]
When checking if a type literal of some type X (e.g. real<4>) is a subtype of the generic type literal type<'a> using insieme::core::types::isSubTypeOf it returns false. However, a literal of type<X> can be passed as argument to a function with parameter type<'a>. Therefore, I think it should also be a subtype.

**Comment by PeterTh** [comment]
I think what you want here is https://github.com/insieme/insieme/blob/fea381f705bad5b903ab4124a781b521b7729732/code/core/src/types/unification.cpp#L303.

**Comment by klois** [comment]
Shouldn't then also the function IRBuilder::deduceReturnTypeForCall https://github.com/insieme/insieme/blob/master/code/core/src/ir_builder.cpp#L890 be based on that? At the moment, when using IRBuilder::callExpr without giving a return type it uses IRBuilder::deduceReturnTypeForCall to deduce it. To do so, it tries to instantiate the types of all parameters using getTypeVariableInstantiation https://github.com/insieme/insieme/blob/master/code/core/src/types/type_variable_deduction.cpp#L542 which checks if the argument types are subtypes of the parameters. As this fails, the return type cannot be deduced and an assertion is thrown by the IRBuilder. 
Should the function  getTypeVariableInstantiation be based on isUnifyable instead of on isSubTypeOf or would that cause other problems?

**Comment by PeterTh** [comment]
We looked into this and found out that it was caused by an incorrect input code.

**Comment by HerbertJordan** [comment]
The return-type deduction should consider type variable instantiations and sub-typing in a combined algorithm. If this is not the case, please let me know.

On the sub-typeing issue: you can not really pass a value of e.g. `type<int<4>>` to a parameter of type `type<'a>`. What you are doing is implicitly instantiating the function such that the argument type is `type<int<4>>`, and the value is then passed to the instantieted version of the function. 

The generic instantiation and the sub-typing are two distinct features, just happening to be both utilized at this point.

Also: whether a value e.g. of type `type<int<4>>` can actually be passed to an argument of type `type<'a>` does not only depend on this pair of argument/parameter types, but also on all the other argument/parameter types in the same call. It may be that the type variable `'a` can be instantiated as `int<4>` or not. This can not be decided localy.
