### ISSUE TITLE
No ref<function type> in Insieme

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#92]
We cannot have things like ```ref<function type>``` in insieme. 
As far as I know this is somehow defined in the IR language spec. 

The problem I have occurs with following input code:
```
bool bla(int n) {
...
}

int main() {
 std::future<bool> res = std::async(bla, 10);
 ...
}
```
The IR async call looks like: 
```
... = ( var(std::async(RefIRToCpp(bla), RefIRToRValCpp(( var(10))));
```
The semantic checks will fail because the ```RefIRToCpp(bla)``` call takes a 
```ref<'a>``` but we do not have ```ref<function type>``` in IR.

**Comment by HerbertJordan** [comment]
Why shouldn't we have such a thing?

**Comment by stefanmoosbrugger** [comment]
fixed with https://github.com/insieme/insieme/commit/6f30908ff60876393d1e99a899ff546cafd0d686
