### ISSUE TITLE
Get rid of __insieme_bool_dummy member field

### ISSUE THREAD

**Issue by stefanmoosbrugger** [insieme/insieme#96]
In order to support async calls that are using lambda 
expressions (e.g., ```std::async([](void) { doSomething(); });```)
I had to introduce a dirty fix that should be removed somehow.

The problem is that a lambda expression turns into a struct that
looks like:
 ```
struct __insieme_lambda {
    //captures
    ...
    //operator(...) member function
    T operator(...) { ... }
};
 ```

In the end the call to the lambda looks like:
```(__insieme_lambda){ /*capture inits*/ }.operator()(...);```

This works fine for structs that contain one or more member fields
but if we have an empty struct (e.g., lambda that captures nothing) the 
curly bracket initialization results in a compiler error (in this case 
the code looks like: ```(__insieme_lambda){ }.operator()();```).

Therefore I introduced a boolean dummy member field that 
is added to the struct if the lambda would be empty. Unsurprisingly
this is not a good solution and we should get rid of this thing.
Any ideas how we can fix the empty lambda init without dummy fields?!

**Comment by HerbertJordan** [comment]
This should be very simple to fix in the backend.

If you have to initialize an empty struct, you can do something like
```
((empty*)(0))->operator()();
```
which should do the trick. This should be a 5-liner. All the constructs you need for that should already be there.

**Comment by stefanmoosbrugger** [comment]
Thx, Herbert. Looks a little bit more ugly, but works fine. Fixed with https://github.com/insieme/insieme/commit/6e5cf022cb47f003c97a7a70246527606fa04187
