### ISSUE TITLE
Automatic logging filtering per namespace/class/function

### ISSUE THREAD

**Issue by PeterTh** [insieme/insieme#98]
At the current size of the project, global logging settings lose their usefulness since as soon as you enable e.g. "DEBUG" logging (never mind verbose!) you simply get too much output you don't care about. This results in either
- every more involved debug session in the compiler manually adding lots of one-shot logging output (which gets deleted before commit), or
- the proliferation of `const static bool debug` variables in each function/method for fine-grained control.

Both of these options suck. The first one implies duplicate or triplicate effort, the second one requires recompilation and a manual solution per function.

Many larger projects I have seen start resolving this by introducing logging namespaces. Where I've looked at the implementation, it's either done manually (adding a qualifier to each log output) or using a specific preprocessing step which adds relevant metainformation. Both of these are too heavyweight.

What I propose is to use the GCC (and Clang) built-in `__PRETTY_FUNCTION__` in the logging macros, pass it to the logger, and add the ability to specify e.g. a regexp-based filter which is matched against these strings. 

Then, if you figure out you want to have the logging output for functions `fooA` and `fooB`, as well as every method in the `Bla` class, you'd simply specify e.g. `fooA|fooB|Bla::` as the filter and get everything you want, and nothing else. Without recompiling every time you want to see something else or writing your own impromptu logging.

I think the only reason not to do this is that `__PRETTY_FUNCTION__` is non-standard, but it is supported in both of our target compilers, and we could even treat it like e.g. `unused` for other potential compilers -- this would just cause the log filtering to not work for those. 

Unless someone has an objection I'll implement this in the near future.

**Comment by HerbertJordan** [comment]
Great idea. In connection with this we should also remove (or regulate) logging levels. Do we need more than on/off?

Also, to make sure nobody relies on side effects of outputs I'd prefer logging only being enabled in the debug built.

**Comment by HerbertJordan** [comment]
Maybe we could also connect it to this [backtracing](http://www.gnu.org/software/libc/manual/html_node/Backtraces.html) feature of GCC so that we can trace all the loges starting from some entry-function.

**Comment by PeterTh** [comment]
Sounds feasible, I'd do this as a separate second step though.

**Comment by PeterTh** [comment]
Implemented in https://github.com/insieme/insieme/commit/ba2c3db95269d442e117a24ad3a566cbfb77850d.
